import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { financeApi } from "@/lib/api";

type Dashboard = any;
const input = "field-input";
const button = "rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition hover:opacity-90 disabled:opacity-50";
const subtleButton = "rounded-xl border border-border bg-secondary/40 px-3 py-2 text-xs font-semibold text-foreground transition hover:bg-secondary";
const today = () => new Date().toISOString().slice(0, 10);
const isoDate = (value: FormDataEntryValue | null) => new Date(String(value ?? today())).toISOString();
const rupees = (value: unknown) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value ?? 0));
const dateLabel = (value: string) => new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
const dateInput = (value: string) => value.slice(0,10);
const number = (form: FormData, name: string) => Number(form.get(name));

function Panel({ title, detail, children, className = "" }: { title: string; detail?: string; children: ReactNode; className?: string }) {
  return <section className={`glass-card rounded-3xl p-5 sm:p-6 ${className}`}>
    <div className="mb-5 flex items-start justify-between gap-3"><div><h2 className="font-display text-lg font-bold">{title}</h2>{detail && <p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</div></div>
    {children}
  </section>;
}

function AddForm({ title, children, onSubmit }: { title: string; children: ReactNode; onSubmit: (form: FormData) => Promise<void> }) {
  return <details className="group mt-4 rounded-2xl border border-border bg-secondary/20 p-3">
    <summary className="cursor-pointer list-none text-sm font-semibold text-primary">+ {title}</summary>
    <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form=event.currentTarget; await onSubmit(new FormData(form)); form.reset(); }}>
      {children}<div className="sm:col-span-2"><button className={button} type="submit">Save</button></div>
    </form>
  </details>;
}

function Field({ label, name, type = "text", required = true, min, step, defaultValue }: { label: string; name: string; type?: string; required?: boolean; min?: string; step?: string; defaultValue?: string }) {
  return <label className="grid gap-1.5"><span className="field-label">{label}</span><input className={input} name={name} type={type} required={required} min={min} step={step} defaultValue={defaultValue} /></label>;
}
function SelectField({ label, name, options }: { label: string; name: string; options: [string, string][] }) {
  return <label className="grid gap-1.5"><span className="field-label">{label}</span><select className={input} name={name}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>;
}
function Empty({ children = "Nothing here yet. Add your first entry to get started." }: { children?: string }) { return <p className="rounded-2xl border border-dashed border-border px-4 py-5 text-sm text-muted-foreground">{children}</p>; }

export function FinanceDashboard() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [entries, setEntries] = useState<any[]>([]);
  const [filters, setFilters] = useState({ month: new Date().toISOString().slice(0, 7), type: "", category: "" });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setError(""); setData(await financeApi.dashboard()); } catch (e) { setError(e instanceof Error ? e.message : "Could not load your finance data"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { let active=true; financeApi.transactions(filters).then(rows=>{if(active)setEntries(rows);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load transactions");}); return ()=>{active=false;}; }, [filters]);

  async function run(action: () => Promise<unknown>) { setError(""); try { await action(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save that entry"); } }
  async function createAccount(f: FormData) { await run(() => financeApi.createAccount({ name:f.get("name"), type:f.get("type"), balance:number(f,"balance") })); }
  async function createIncome(f: FormData) { await run(() => financeApi.createIncome({ name:f.get("name"), type:f.get("type"), amount:number(f,"amount"), frequency:f.get("frequency"), effectiveFrom:isoDate(f.get("effectiveFrom")) })); }
  async function createTransaction(f: FormData) { await run(() => financeApi.createTransaction({ accountId:f.get("accountId"), type:f.get("type"), amount:number(f,"amount"), category:f.get("category"), description:f.get("description"), date:isoDate(f.get("date")) })); }
  async function createLoan(f: FormData) { await run(() => financeApi.createLoan({ type:f.get("type"), principal:number(f,"principal"), interestRate:number(f,"interestRate"), tenureMonths:number(f,"tenureMonths"), outstanding:number(f,"outstanding"), startDate:isoDate(f.get("startDate")) })); }
  async function createBudget(f: FormData) { await run(() => financeApi.createBudget({ goalName:f.get("goalName"), targetAmount:number(f,"targetAmount"), currentAmount:number(f,"currentAmount"), targetDate:isoDate(f.get("targetDate")) })); }
  async function createBill(f: FormData) { await run(() => financeApi.createBill({ name:f.get("name"), amount:number(f,"amount"), category:f.get("category"), dueDate:isoDate(f.get("dueDate")), recurrence:f.get("recurrence") })); }
  async function saveCreditScore(f: FormData) { await run(() => financeApi.setCreditScore(number(f,"score"))); }

  if (loading) return <div className="glass-card rounded-3xl p-8 text-center text-sm text-muted-foreground">Loading your finance dashboard…</div>;
  if (!data) return <div className="glass-card rounded-3xl p-6"><p className="text-sm text-destructive">{error || "Dashboard unavailable"}</p><button className={`${subtleButton} mt-4`} onClick={() => { setLoading(true); void load(); }}>Try again</button></div>;
  const o = data.overview;
  const metrics: [string,string,string][] = [
    ["Monthly income",rupees(o.monthlyIncome),`${data.incomeSources.length} active source${data.incomeSources.length===1?"":"s"}`],
    ["Monthly expenses",rupees(o.monthlyExpenses),data.month],
    ["Net worth",rupees(o.netWorth),o.netWorthChange===null?"Monthly comparison starts next month":`${o.netWorthChange>=0?"↑":"↓"} ${rupees(Math.abs(o.netWorthChange))} vs last month`],
    ["Savings rate",o.savingsRate===null?"—":`${o.savingsRate.toFixed(1)}%`,"Income minus tracked expenses"],
  ];
  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3 px-1"><div><p className="field-label">Your money, in one place</p><h2 className="font-display mt-1 text-2xl font-bold">Finance overview</h2><p className="mt-1 text-sm text-muted-foreground">{data.user.firstName ? `Welcome, ${data.user.firstName}. ` : ""}{new Date(`${data.month}-01`).toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</p></div><button className={subtleButton} onClick={()=>{setLoading(true);void load();}}>Refresh</button></div>
    {error && <div role="alert" className="rounded-2xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,sub])=><div key={label} className="glass-card rounded-2xl p-4"><p className="field-label">{label}</p><p className="font-display mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{sub}</p></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <Panel title="Accounts and assets" detail={`${rupees(o.assets)} total assets · cash balances and investment values`}>
        {data.accounts.length ? <div className="space-y-2">{data.accounts.map((a:any)=><div key={a.id} className="flex items-center justify-between rounded-xl bg-secondary/30 px-3 py-3"><div><p className="text-sm font-semibold">{a.name}</p><p className="text-xs text-muted-foreground">{a.type.replaceAll("_"," ")}</p></div><div className="flex items-center gap-2"><b className="text-sm">{rupees(a.balance)}</b><details className="relative"><summary className={`${subtleButton} list-none cursor-pointer`}>Edit</summary><form className="absolute right-0 z-10 mt-2 grid w-64 gap-2 rounded-2xl border border-border bg-card p-3 shadow-xl" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>financeApi.updateAccount(a.id,{name:f.get("name"),type:f.get("type"),balance:number(f,"balance")}));}}><Field label="Account name" name="name" defaultValue={a.name}/><SelectField label="Type" name="type" options={[["CHECKING","Checking"],["SAVINGS","Savings"],["SALARY","Salary account"],["FD","Fixed deposit"]]}/><Field label="Current balance (₹)" name="balance" type="number" min="0" step="0.01" defaultValue={String(a.balance)}/><button className={button}>Save changes</button></form></details></div></div>)}</div> : <Empty>No accounts yet. Add an account to record expenses and cash assets.</Empty>}
        {data.investments.length>0 && <div className="mt-3 space-y-2">{data.investments.map((i:any)=><div key={i.id} className="flex items-center justify-between rounded-xl border border-border px-3 py-3"><div><p className="text-sm font-semibold">{i.name}</p><p className="text-xs text-muted-foreground">Investment · {i.category.replaceAll("_"," ")}</p></div><div className="text-right"><b className="text-sm">{rupees(i.currentValue)}</b><p className={`text-xs ${Number(i.currentValue)-Number(i.investedAmount)>=0?"text-primary":"text-destructive"}`}>{Number(i.currentValue)-Number(i.investedAmount)>=0?"+":""}{rupees(Number(i.currentValue)-Number(i.investedAmount))} P&amp;L</p></div></div>)}</div>}
        <AddForm title="Add an account" onSubmit={createAccount}><Field label="Account name" name="name"/><SelectField label="Type" name="type" options={[["CHECKING","Checking"],["SAVINGS","Savings"],["SALARY","Salary account"],["FD","Fixed deposit"]]}/><Field label="Current balance (₹)" name="balance" type="number" min="0" step="0.01"/></AddForm>
      </Panel>
      <Panel title="Financial health" detail="A 0–100 guide from savings, debt load, and emergency cover">
        <div className="flex items-center gap-5"><div className="grid size-24 shrink-0 place-items-center rounded-full border-[6px] border-primary/70 bg-primary/10"><span className="font-display text-3xl font-bold">{o.healthScore}</span></div><div><p className="font-semibold">{o.healthScore>=75?"Strong habits":o.healthScore>=45?"Building momentum":"Room to improve"}</p><p className="mt-1 text-xs text-muted-foreground">Calculated from the current month’s recorded data.</p></div></div>
        <div className="mt-5 space-y-3">{[["Savings rate",o.healthBreakdown.savingsRate,40,o.healthBreakdown.savingsRatePercent==null?"No income recorded":`${o.healthBreakdown.savingsRatePercent.toFixed(1)}%`],["Debt-to-income",o.healthBreakdown.debtToIncome,30,o.healthBreakdown.debtToIncomePercent==null?"No income recorded":`${o.healthBreakdown.debtToIncomePercent.toFixed(1)}%`],["Emergency fund",o.healthBreakdown.emergencyFund,30,o.healthBreakdown.emergencyFundMonths==null?"Add expenses to calculate":`${o.healthBreakdown.emergencyFundMonths.toFixed(1)} months`]].map(([label,score,max,desc]:any)=><div key={label}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><span className="text-muted-foreground">{desc} · {score}/{max}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,Number(score)/Number(max)*100)}%`}}/></div></div>)}</div>
      </Panel>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <Panel title="Income sources" detail="Recurring income normalized to a monthly estimate">
        {data.incomeSources.length?<div className="space-y-2">{data.incomeSources.map((s:any)=><div key={s.id} className="flex items-center justify-between rounded-xl bg-secondary/30 px-3 py-3"><div><p className="text-sm font-semibold">{s.name}</p><p className="text-xs text-muted-foreground">{s.type.toLowerCase()} · {s.frequency.toLowerCase()}</p></div><div className="flex items-center gap-3"><b className="text-sm">{rupees(s.amount)}</b><details className="relative"><summary className={`${subtleButton} list-none cursor-pointer`}>Edit</summary><form className="absolute right-0 z-10 mt-2 grid w-64 gap-2 rounded-2xl border border-border bg-card p-3 shadow-xl" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>financeApi.updateIncome(s.id,{amount:number(f,"amount"),frequency:f.get("frequency")}));}}><Field label="Amount (₹)" name="amount" type="number" min="0.01" step="0.01" defaultValue={String(s.amount)}/><SelectField label="Frequency" name="frequency" options={[["MONTHLY","Monthly"],["WEEKLY","Weekly"],["ANNUAL","Annual"]]}/><button className={button}>Save changes</button></form></details><button className={subtleButton} onClick={()=>void run(()=>financeApi.deleteIncome(s.id))}>Remove</button></div></div>)}</div>:<Empty/>}
        <AddForm title="Add income source" onSubmit={createIncome}><Field label="Name" name="name"/><SelectField label="Type" name="type" options={[["SALARY","Salary"],["FREELANCE","Freelance"],["RENTAL","Rental"],["OTHER","Other"]]}/><Field label="Amount (₹)" name="amount" type="number" min="0.01" step="0.01"/><SelectField label="Frequency" name="frequency" options={[["MONTHLY","Monthly"],["WEEKLY","Weekly"],["ANNUAL","Annual"]]}/><Field label="Starts on" name="effectiveFrom" type="date" defaultValue={today()}/></AddForm>
      </Panel>
      <Panel title="Transactions" detail="Recent entries, with month, category, and type recorded">
        <div className="mb-3 grid grid-cols-3 gap-2"><input aria-label="Filter month" className={input} type="month" value={filters.month} onChange={e=>setFilters({...filters,month:e.target.value})}/><select aria-label="Filter type" className={input} value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">All types</option><option value="INCOME">Income</option><option value="EXPENSE">Expenses</option></select><input aria-label="Filter category" className={input} placeholder="Category" value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}/></div>
        {entries.length?<div className="max-h-72 space-y-2 overflow-auto">{entries.map((t:any)=><div key={t.id} className="flex items-center justify-between gap-3 rounded-xl bg-secondary/30 px-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{t.description||t.category}</p><p className="text-xs text-muted-foreground">{t.category} · {t.account.name} · {dateLabel(t.date)}</p></div><div className="flex shrink-0 items-center gap-2"><b className={`text-sm ${t.type==="INCOME"?"text-primary":""}`}>{t.type==="INCOME"?"+":"−"}{rupees(t.amount)}</b><details className="relative"><summary className={`${subtleButton} list-none cursor-pointer`}>Edit</summary><form className="absolute right-0 z-10 mt-2 grid w-64 gap-2 rounded-2xl border border-border bg-card p-3 shadow-xl" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>financeApi.updateTransaction(t.id,{type:f.get("type"),amount:number(f,"amount"),category:f.get("category"),description:f.get("description"),date:isoDate(f.get("date"))}));}}><SelectField label="Type" name="type" options={[["EXPENSE","Expense"],["INCOME","Income"]]}/><Field label="Amount (₹)" name="amount" type="number" min="0.01" step="0.01" defaultValue={String(t.amount)}/><Field label="Category" name="category" defaultValue={t.category}/><Field label="Description" name="description" defaultValue={t.description}/><Field label="Date" name="date" type="date" defaultValue={dateInput(t.date)}/><button className={button}>Save changes</button></form></details><button className={subtleButton} aria-label="Delete transaction" onClick={()=>void run(()=>financeApi.deleteTransaction(t.id))}>×</button></div></div>)}</div>:<Empty>No transactions match these filters.</Empty>}
        {data.accounts.length>0?<AddForm title="Record a transaction" onSubmit={createTransaction}><SelectField label="Account" name="accountId" options={data.accounts.map((a:any)=>[a.id,a.name])}/><SelectField label="Type" name="type" options={[["EXPENSE","Expense"],["INCOME","Income"]]}/><Field label="Amount (₹)" name="amount" type="number" min="0.01" step="0.01"/><Field label="Category" name="category"/><Field label="Description" name="description"/><Field label="Date" name="date" type="date" defaultValue={today()}/></AddForm>:<p className="mt-3 text-xs text-muted-foreground">Add an account before recording transactions.</p>}
      </Panel>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <Panel title="Loans and liabilities" detail={`${rupees(o.liabilities)} outstanding · EMI total ${rupees(data.loans.reduce((s:number,l:any)=>s+Number(l.emiAmount),0))} per month`}>
        {data.loans.length?<div className="space-y-2">{data.loans.map((l:any)=><div key={l.id} className="flex items-center justify-between gap-2 rounded-xl bg-secondary/30 px-3 py-3"><div><p className="text-sm font-semibold">{l.type.replaceAll("_"," ")} loan</p><p className="text-xs text-muted-foreground">{Number(l.interestRate)}% · {l.tenureMonths} months · EMI {rupees(l.emiAmount)}</p></div><div className="flex items-center gap-2"><b className="text-sm">{rupees(l.outstanding)}</b><details className="relative"><summary className={`${subtleButton} list-none cursor-pointer`}>Edit</summary><form className="absolute right-0 z-10 mt-2 grid w-64 gap-2 rounded-2xl border border-border bg-card p-3 shadow-xl" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>financeApi.updateLoan(l.id,{outstanding:number(f,"outstanding"),interestRate:number(f,"interestRate")}));}}><Field label="Outstanding (₹)" name="outstanding" type="number" min="0" step="0.01" defaultValue={String(l.outstanding)}/><Field label="Interest rate (% p.a.)" name="interestRate" type="number" min="0" step="0.01" defaultValue={String(l.interestRate)}/><button className={button}>Save changes</button></form></details><button className={subtleButton} onClick={()=>void run(()=>financeApi.deleteLoan(l.id))}>Remove</button></div></div>)}</div>:<Empty>No loans recorded.</Empty>}
        <AddForm title="Add loan" onSubmit={createLoan}><SelectField label="Loan type" name="type" options={[["HOME","Home"],["AUTO","Vehicle"],["GOLD","Gold"],["PERSONAL","Personal"]]}/><Field label="Original principal (₹)" name="principal" type="number" min="0.01" step="0.01"/><Field label="Interest rate (% p.a.)" name="interestRate" type="number" min="0" step="0.01"/><Field label="Tenure (months)" name="tenureMonths" type="number" min="1"/><Field label="Outstanding (₹)" name="outstanding" type="number" min="0" step="0.01"/><Field label="Start date" name="startDate" type="date" defaultValue={today()}/></AddForm>
      </Panel>
      <Panel title="Goal-based budget planner" detail="Monthly amount needed to reach each target by its date">
        {data.budgets.length?<div className="space-y-3">{data.budgets.map((b:any)=><div key={b.id} className="rounded-xl bg-secondary/30 p-3"><div className="flex justify-between gap-2"><div><p className="text-sm font-semibold">{b.goalName}</p><p className="text-xs text-muted-foreground">{rupees(b.currentAmount)} of {rupees(b.targetAmount)} · due {dateLabel(b.targetDate)}</p></div><button className={subtleButton} onClick={()=>void run(()=>financeApi.deleteBudget(b.id))}>Remove</button></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${b.progressPercent}%`}}/></div><p className="mt-2 text-xs text-muted-foreground">Save about {rupees(b.requiredMonthlySaving)} per month (0% return assumption)</p><form className="mt-2 grid gap-2 sm:grid-cols-[1fr_1fr_auto]" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>financeApi.updateBudget(b.id,{currentAmount:number(f,"currentAmount"),targetAmount:number(f,"targetAmount"),targetDate:isoDate(f.get("targetDate"))}));}}><input aria-label="Current saved amount" className={input} name="currentAmount" type="number" min="0" step="0.01" defaultValue={Number(b.currentAmount)}/><input aria-label="Goal target amount" className={input} name="targetAmount" type="number" min="0.01" step="0.01" defaultValue={Number(b.targetAmount)}/><button className={subtleButton}>Update goal</button><input aria-label="Goal target date" className={`${input} sm:col-span-2`} name="targetDate" type="date" defaultValue={dateInput(b.targetDate)}/></form></div>)}</div>:<Empty/>}
        <AddForm title="Add a savings goal" onSubmit={createBudget}><Field label="Goal" name="goalName"/><Field label="Target amount (₹)" name="targetAmount" type="number" min="0.01" step="0.01"/><Field label="Already saved (₹)" name="currentAmount" type="number" min="0" step="0.01" defaultValue="0"/><Field label="Target date" name="targetDate" type="date"/></AddForm>
      </Panel>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <Panel title="Monthly spending by category" detail="Expenses recorded for the current month">
        {data.expenseCategories.length ? <div className="space-y-3">{data.expenseCategories.slice(0,6).map((c:any)=><div key={c.category}><div className="mb-1 flex justify-between text-xs"><span>{c.category}</span><span className="text-muted-foreground">{rupees(c.amount)}</span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${Math.max(3,Number(c.amount)/Number(data.expenseCategories[0].amount)*100)}%`}}/></div></div>)}</div> : <Empty>Add categorized expenses to see the breakdown.</Empty>}
      </Panel>
      <Panel title="Assets and liabilities" detail={`${rupees(o.assets)} assets against ${rupees(o.liabilities)} liabilities`}>
        <div className="space-y-4"><div><p className="mb-2 field-label">Assets</p>{data.assetBreakdown.length?data.assetBreakdown.map((v:any)=><div key={v.type} className="mb-2"><div className="mb-1 flex justify-between text-xs"><span>{String(v.type).replaceAll("_"," ")}</span><span>{rupees(v.value)}</span></div><div className="h-1.5 rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${Math.max(2,Number(v.value)/Math.max(1,o.assets)*100)}%`}}/></div></div>):<p className="text-xs text-muted-foreground">Add accounts or investments.</p>}</div><div><p className="mb-2 field-label">Liabilities</p>{data.liabilityBreakdown.length?data.liabilityBreakdown.map((v:any)=><div key={v.type} className="mb-2"><div className="mb-1 flex justify-between text-xs"><span>{String(v.type).replaceAll("_"," ")}</span><span>{rupees(v.value)}</span></div><div className="h-1.5 rounded-full bg-secondary"><div className="h-full rounded-full bg-chart-2" style={{width:`${Math.max(2,Number(v.value)/Math.max(1,o.liabilities)*100)}%`}}/></div></div>):<p className="text-xs text-muted-foreground">No liabilities recorded.</p>}</div></div>
      </Panel>
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <Panel title="Bills and subscriptions" detail="Upcoming bills show the next 30 days; recurring entries are marked for planning">
        {data.bills.length?<div className="space-y-2">{data.bills.map((b:any)=><div key={b.id} className="flex items-center justify-between gap-3 rounded-xl bg-secondary/30 px-3 py-3"><div><p className="text-sm font-semibold">{b.name}{b.category.toLowerCase().includes("subscription")&&<span className="ml-2 rounded-full bg-primary/10 px-2 py-0.5 text-[10px] text-primary">SUBSCRIPTION</span>}</p><p className="text-xs text-muted-foreground">{b.category} · {b.recurrence.toLowerCase()} · due {dateLabel(b.dueDate)}{b.isPaid?" · paid":""}</p></div><div className="flex items-center gap-2"><b className="text-sm">{rupees(b.amount)}</b><button className={subtleButton} onClick={()=>void run(()=>financeApi.updateBill(b.id,{isPaid:!b.isPaid}))}>{b.isPaid?"Undo":"Paid"}</button><details className="relative"><summary className={`${subtleButton} list-none cursor-pointer`}>Edit</summary><form className="absolute right-0 z-10 mt-2 grid w-64 gap-2 rounded-2xl border border-border bg-card p-3 shadow-xl" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>financeApi.updateBill(b.id,{name:f.get("name"),amount:number(f,"amount"),category:f.get("category"),recurrence:f.get("recurrence"),dueDate:isoDate(f.get("dueDate"))}));}}><Field label="Name" name="name" defaultValue={b.name}/><Field label="Amount (₹)" name="amount" type="number" min="0.01" step="0.01" defaultValue={String(b.amount)}/><Field label="Category" name="category" defaultValue={b.category}/><SelectField label="Repeats" name="recurrence" options={[["MONTHLY","Monthly"],["QUARTERLY","Quarterly"],["ANNUAL","Annual"]]}/><Field label="Due date" name="dueDate" type="date" defaultValue={dateInput(b.dueDate)}/><button className={button}>Save changes</button></form></details><button className={subtleButton} onClick={()=>void run(()=>financeApi.deleteBill(b.id))}>×</button></div></div>)}</div>:<Empty/>}
        {data.upcomingBills.length>0&&<p className="mt-3 rounded-xl border border-primary/20 bg-primary/5 px-3 py-2 text-xs text-primary">{data.upcomingBills.length} bill{data.upcomingBills.length===1?"":"s"} due in the next 30 days · {rupees(data.upcomingBills.reduce((s:number,b:any)=>s+Number(b.amount),0))} total</p>}
        <AddForm title="Add bill or subscription" onSubmit={createBill}><Field label="Name" name="name"/><Field label="Amount (₹)" name="amount" type="number" min="0.01" step="0.01"/><SelectField label="Category" name="category" options={[["UTILITIES","Utilities"],["SUBSCRIPTION","Subscription"],["INSURANCE","Insurance"],["OTHER","Other"]]}/><SelectField label="Repeats" name="recurrence" options={[["MONTHLY","Monthly"],["QUARTERLY","Quarterly"],["ANNUAL","Annual"]]}/><Field label="Next due date" name="dueDate" type="date" defaultValue={today()}/></AddForm>
      </Panel>
      <div className="space-y-5">
        <Panel title="Credit score" detail="Personal display only; update when you check your score">
          <div className="flex items-end justify-between"><div><p className="font-display text-4xl font-bold">{o.creditScore??"—"}</p><p className="mt-1 text-xs text-muted-foreground">{o.creditScore==null?"No score entered":Number(o.creditScore)>=750?"Excellent":Number(o.creditScore)>=700?"Good":Number(o.creditScore)>=650?"Fair":"Needs attention"} · out of 900</p></div>{o.creditScore!=null&&<span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">Self reported</span>}</div>
          <AddForm title={o.creditScore==null?"Enter score":"Update score"} onSubmit={saveCreditScore}><Field label="Score (300–900)" name="score" type="number" min="300" step="1" defaultValue={o.creditScore==null?undefined:String(o.creditScore)}/></AddForm>
        </Panel>
        <Panel title="Recurring patterns" detail="Possible recurring spend inferred from repeated transaction descriptions">
          {data.detectedRecurring.length?<div className="space-y-2">{data.detectedRecurring.map((r:any)=><div key={r.label} className="flex items-center justify-between rounded-xl bg-secondary/30 px-3 py-3"><div><p className="text-sm font-semibold capitalize">{r.label}</p><p className="text-xs text-muted-foreground">Seen {r.count} times · latest {dateLabel(r.lastDate)}</p></div><b className="text-sm">~{rupees(r.typicalAmount)}</b></div>)}</div>:<Empty>No repeated transaction descriptions found yet.</Empty>}
        </Panel>
      </div>
    </div>
  </div>;
}
