GET http://localhost:3000/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYjc3YTc0Mi04OTc5LTQwYTMtODJjOC1mNjJiYTg1ZDA5NDEiLCJpYXQiOjE3OTA0Mjk2MjEsImV4cCI6MTc5MDQzMDUyMX0.o7KeBzivNrIB4RiKfaNz5fv0KTC89u14tAx6q2FSRQo